---
apiVersion: v1
kind: Service
metadata:
  name: myip
  labels:
    service: myip
spec:
  ports:
    - name: tcp
      port: 8080
      targetPort: 8080
      nodePort: 30005
      protocol: TCP
  type: NodePort
  selector:
    service: myip
