---
apiVersion: v1
kind: Service
metadata:
  name: gitea
  labels:
    service: gitea
spec:
  ports:
    - name: web
      port: 3000
      targetPort: 3000
      nodePort: 30003
      protocol: TCP
    - name: ssh
      port: 22
      targetPort: 22
      nodePort: 30200
      protocol: TCP
  type: NodePort
  selector:
    service: gitea
