---
apiVersion: v1
kind: Service
metadata:
  name: unbound
  labels:
    service: app
spec:
  ports:
    - name: udp
      port: 53
      targetPort: 53
      protocol: UDP
    - name: tcp
      port: 53
      targetPort: 53
      protocol: TCP
  type: ClusterIP
  selector:
    service: unbound

---
apiVersion: v1
kind: Service
metadata:
  name: unbound-nodeport
  labels:
    service: app
spec:
  ports:
    - name: udp
      port: 53
      targetPort: 53
      nodePort: 30102
      protocol: UDP
  type: NodePort
  selector:
    service: unbound