---
apiVersion: v1
kind: Service
metadata:
  name: file-server
  labels:
    service: file-server
spec:
  ports:
    - name: web
      port: 8000
      targetPort: 8000
      nodePort: 30004
      protocol: TCP
  type: NodePort
  selector:
    service: file-server
